name: Build-Windows
on: push
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Anarchy
        uses: actions/checkout@v2
      - name: Get submodules
        run: git submodule update --init --progress --depth 1
        shell: cmd
      - name: Generate projects
        run: ./Win-GenProjects.bat
        working-directory: Scripts
        shell: cmd
      - name: Build Anarchy
        run: '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe" Anarchy.sln -m'
        shell: cmd